// Maps GeoJSON district_name (older/DHS naming) to Data Store DistrictName (current official spelling)
export const GEOJSON_TO_DB_NAME = {
  'Bagalkot': 'Bagalkot',
  'Bangalore': 'Bengaluru Urban',
  'Bangalore Rural': 'Bengaluru Rural',
  'Belgaum': 'Belagavi',
  'Bellary': 'Ballari',
  'Bidar': 'Bidar',
  'Bijapur': 'Vijayapura',
  'Chamarajanagar': 'Chamarajanagar',
  'Chikkaballapura': 'Chikballapur',
  'Chikmagalur': 'Chikkamagaluru',
  'Chitradurga': 'Chitradurga',
  'Dakshina Kannada': 'Mangaluru',
  'Davanagere': 'Davanagere',
  'Dharwad': 'Hubballi-Dharwad',
  'Gadag': 'Gadag',
  'Gulbarga': 'Kalaburagi',
  'Hassan': 'Hassan',
  'Haveri': 'Haveri',
  'Kodagu': 'Kodagu',
  'Kolar': 'Kolar',
  'Koppal': 'Koppal',
  'Mandya': 'Mandya',
  'Mysore': 'Mysuru',
  'Raichur': 'Raichur',
  'Ramanagara': 'Ramanagara',
  'Shimoga': 'Shivamogga',
  'Tumkur': 'Tumakuru',
  'Udupi': 'Udupi',
  'Uttara Kannada': 'Uttara Kannada',
  'Yadgir': 'Yadgir'
  // Note: Vijayanagara has no polygon in this dataset — it was split from Bellary after this data was made
};